(* Generated by rocq-of-solidity *)
Require Import RocqOfSolidity.RocqOfSolidity.

Module C.
  Definition code : Code.t := {|
    Code.name := "C_84";
    Code.hex_name := 0x435f383400000000000000000000000000000000000000000000000000000000;
    Code.functions :=
      [
        
      ];
    Code.body :=
      M.scope (
        do! ltac:(M.monadic (
          M.scope (
            do! ltac:(M.monadic (
              M.declare (|
                ["_1"],
                Some (M.call_function (|
                  "memoryguard",
                  [
                    [Literal.number 0x80]
                  ]
                |))
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "mstore",
                  [
                    [Literal.number 64];
                    M.get_var (| "_1" |)
                  ]
                |)
              |)
            )) in
            do! ltac:(M.monadic (
              M.if_ (|
                M.call_function (|
                  "callvalue",
                  []
                |),
                M.scope (
                  do! ltac:(M.monadic (
                    M.expr_stmt (|
                      M.call_function (|
                        "revert",
                        [
                          [Literal.number 0];
                          [Literal.number 0]
                        ]
                      |)
                    |)
                  )) in
                  M.pure BlockUnit.Tt
                )
              |)
            )) in
            do! ltac:(M.monadic (
              M.declare (|
                ["_2"],
                Some (M.call_function (|
                  "datasize",
                  [
                    [Literal.string 0x435f38345f6465706c6f79656400000000000000000000000000000000000000]
                  ]
                |))
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "codecopy",
                  [
                    M.get_var (| "_1" |);
                    M.call_function (|
                      "dataoffset",
                      [
                        [Literal.string 0x435f38345f6465706c6f79656400000000000000000000000000000000000000]
                      ]
                    |);
                    M.get_var (| "_2" |)
                  ]
                |)
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "return",
                  [
                    M.get_var (| "_1" |);
                    M.get_var (| "_2" |)
                  ]
                |)
              |)
            )) in
            M.pure BlockUnit.Tt
          )
        )) in
        M.pure BlockUnit.Tt
      );
  |}.

  Module deployed.
    Definition code : Code.t := {|
      Code.name := "C_84_deployed";
      Code.hex_name := 0x435f38345f6465706c6f79656400000000000000000000000000000000000000;
      Code.functions :=
        [
          Code.Function.make (
            "finalize_allocation",
            ["memPtr"; "size"],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.declare (|
                  ["newFreePtr"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "memPtr" |);
                      M.call_function (|
                        "and",
                        [
                          M.call_function (|
                            "add",
                            [
                              M.get_var (| "size" |);
                              [Literal.number 31]
                            ]
                          |);
                          M.call_function (|
                            "not",
                            [
                              [Literal.number 31]
                            ]
                          |)
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "or",
                    [
                      M.call_function (|
                        "gt",
                        [
                          M.get_var (| "newFreePtr" |);
                          [Literal.number 0xffffffffffffffff]
                        ]
                      |);
                      M.call_function (|
                        "lt",
                        [
                          M.get_var (| "newFreePtr" |);
                          M.get_var (| "memPtr" |)
                        ]
                      |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 0];
                            M.call_function (|
                              "shl",
                              [
                                [Literal.number 224];
                                [Literal.number 0x4e487b71]
                              ]
                            |)
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 4];
                            [Literal.number 0x41]
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0x24]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      [Literal.number 64];
                      M.get_var (| "newFreePtr" |)
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "erc7201",
            ["namespaceIDDataPtr"; "namespaceIDLength"],
            ["slot"],
            M.scope (
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      [Literal.number 0];
                      M.call_function (|
                        "add",
                        [
                          M.call_function (|
                            "keccak256",
                            [
                              M.get_var (| "namespaceIDDataPtr" |);
                              M.get_var (| "namespaceIDLength" |)
                            ]
                          |);
                          M.call_function (|
                            "not",
                            [
                              [Literal.number 0]
                            ]
                          |)
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["slot"],
                  Some (M.call_function (|
                    "and",
                    [
                      M.call_function (|
                        "keccak256",
                        [
                          [Literal.number 0];
                          [Literal.number 32]
                        ]
                      |);
                      M.call_function (|
                        "not",
                        [
                          [Literal.number 255]
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "fun_erc7201Mock",
            ["var_id_mpos"],
            ["var"],
            M.scope (
              do! ltac:(M.monadic (
                M.declare (|
                  ["_1"],
                  Some (M.call_function (|
                    "keccak256",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "var_id_mpos" |);
                          [Literal.number 0x20]
                        ]
                      |);
                      M.call_function (|
                        "mload",
                        [
                          M.get_var (| "var_id_mpos" |)
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["diff"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "_1" |);
                      M.call_function (|
                        "not",
                        [
                          [Literal.number 0]
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "gt",
                    [
                      M.get_var (| "diff" |);
                      M.get_var (| "_1" |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 0];
                            M.call_function (|
                              "shl",
                              [
                                [Literal.number 224];
                                [Literal.number 0x4e487b71]
                              ]
                            |)
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 4];
                            [Literal.number 0x11]
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0x24]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["outPtr"],
                  Some (M.call_function (|
                    "mload",
                    [
                      [Literal.number 64]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["_2"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "outPtr" |);
                      [Literal.number 0x20]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "_2" |);
                      M.get_var (| "diff" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "outPtr" |);
                      [Literal.number 0x20]
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "finalize_allocation",
                    [
                      M.get_var (| "outPtr" |);
                      [Literal.number 64]
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["var"],
                  Some (M.call_function (|
                    "and",
                    [
                      M.call_function (|
                        "keccak256",
                        [
                          M.get_var (| "_2" |);
                          M.call_function (|
                            "mload",
                            [
                              M.get_var (| "outPtr" |)
                            ]
                          |)
                        ]
                      |);
                      M.call_function (|
                        "not",
                        [
                          [Literal.number 255]
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          )
        ];
      Code.body :=
        M.scope (
          do! ltac:(M.monadic (
            M.scope (
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      [Literal.number 64];
                      M.call_function (|
                        "memoryguard",
                        [
                          [Literal.number 0x80]
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "iszero",
                    [
                      M.call_function (|
                        "lt",
                        [
                          M.call_function (|
                            "calldatasize",
                            []
                          |);
                          [Literal.number 4]
                        ]
                      |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.switch (|
                        M.call_function (|
                          "shr",
                          [
                            [Literal.number 224];
                            M.call_function (|
                              "calldataload",
                              [
                                [Literal.number 0]
                              ]
                            |)
                          ]
                        |),
                        [
                          (
                            Some (Literal.number 0x7f183b57),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "callvalue",
                                    []
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "slt",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.call_function (|
                                            "calldatasize",
                                            []
                                          |);
                                          M.call_function (|
                                            "not",
                                            [
                                              [Literal.number 3]
                                            ]
                                          |)
                                        ]
                                      |);
                                      [Literal.number 64]
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["value"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["value"],
                                  Some (M.call_function (|
                                    "calldataload",
                                    [
                                      [Literal.number 4]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "iszero",
                                    [
                                      M.call_function (|
                                        "eq",
                                        [
                                          M.get_var (| "value" |);
                                          M.call_function (|
                                            "iszero",
                                            [
                                              M.call_function (|
                                                "iszero",
                                                [
                                                  M.get_var (| "value" |)
                                                ]
                                              |)
                                            ]
                                          |)
                                        ]
                                      |)
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["value_1"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["value_1"],
                                  Some (M.call_function (|
                                    "calldataload",
                                    [
                                      [Literal.number 36]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "iszero",
                                    [
                                      M.call_function (|
                                        "eq",
                                        [
                                          M.get_var (| "value_1" |);
                                          M.call_function (|
                                            "iszero",
                                            [
                                              M.call_function (|
                                                "iszero",
                                                [
                                                  M.get_var (| "value_1" |)
                                                ]
                                              |)
                                            ]
                                          |)
                                        ]
                                      |)
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["expr_mpos"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.switch (|
                                  M.get_var (| "value" |),
                                  [
                                    (
                                      Some (Literal.number 0),
                                      M.scope (
                                        do! ltac:(M.monadic (
                                          M.declare (|
                                            ["expr_mpos_1"],
                                            Some ([Literal.number 0])
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.switch (|
                                            M.get_var (| "value_1" |),
                                            [
                                              (
                                                Some (Literal.number 0),
                                                M.scope (
                                                  do! ltac:(M.monadic (
                                                    M.declare (|
                                                      ["memPtr"],
                                                      Some ([Literal.number 0])
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.declare (|
                                                      ["size"],
                                                      Some ([Literal.number 0])
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.assign (|
                                                      ["size"],
                                                      Some ([Literal.number 0])
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.declare (|
                                                      ["memPtr_1"],
                                                      Some (M.call_function (|
                                                        "mload",
                                                        [
                                                          [Literal.number 64]
                                                        ]
                                                      |))
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.expr_stmt (|
                                                      M.call_function (|
                                                        "finalize_allocation",
                                                        [
                                                          M.get_var (| "memPtr_1" |);
                                                          [Literal.number 64]
                                                        ]
                                                      |)
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.assign (|
                                                      ["memPtr"],
                                                      Some (M.get_var (| "memPtr_1" |))
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.expr_stmt (|
                                                      M.call_function (|
                                                        "mstore",
                                                        [
                                                          M.get_var (| "memPtr_1" |);
                                                          [Literal.number 1]
                                                        ]
                                                      |)
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.expr_stmt (|
                                                      M.call_function (|
                                                        "mstore",
                                                        [
                                                          M.call_function (|
                                                            "add",
                                                            [
                                                              M.get_var (| "memPtr_1" |);
                                                              [Literal.number 32]
                                                            ]
                                                          |);
                                                          [Literal.string 0x6300000000000000000000000000000000000000000000000000000000000000]
                                                        ]
                                                      |)
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.assign (|
                                                      ["expr_mpos_1"],
                                                      Some (M.get_var (| "memPtr_1" |))
                                                    |)
                                                  )) in
                                                  M.pure BlockUnit.Tt
                                                )
                                              );
                                              (
                                                None,
                                                M.scope (
                                                  do! ltac:(M.monadic (
                                                    M.declare (|
                                                      ["memPtr_2"],
                                                      Some ([Literal.number 0])
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.declare (|
                                                      ["size_1"],
                                                      Some ([Literal.number 0])
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.assign (|
                                                      ["size_1"],
                                                      Some ([Literal.number 0])
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.declare (|
                                                      ["memPtr_3"],
                                                      Some (M.call_function (|
                                                        "mload",
                                                        [
                                                          [Literal.number 64]
                                                        ]
                                                      |))
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.expr_stmt (|
                                                      M.call_function (|
                                                        "finalize_allocation",
                                                        [
                                                          M.get_var (| "memPtr_3" |);
                                                          [Literal.number 64]
                                                        ]
                                                      |)
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.assign (|
                                                      ["memPtr_2"],
                                                      Some (M.get_var (| "memPtr_3" |))
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.expr_stmt (|
                                                      M.call_function (|
                                                        "mstore",
                                                        [
                                                          M.get_var (| "memPtr_3" |);
                                                          [Literal.number 1]
                                                        ]
                                                      |)
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.expr_stmt (|
                                                      M.call_function (|
                                                        "mstore",
                                                        [
                                                          M.call_function (|
                                                            "add",
                                                            [
                                                              M.get_var (| "memPtr_3" |);
                                                              [Literal.number 32]
                                                            ]
                                                          |);
                                                          [Literal.string 0x7800000000000000000000000000000000000000000000000000000000000000]
                                                        ]
                                                      |)
                                                    |)
                                                  )) in
                                                  do! ltac:(M.monadic (
                                                    M.assign (|
                                                      ["expr_mpos_1"],
                                                      Some (M.get_var (| "memPtr_3" |))
                                                    |)
                                                  )) in
                                                  M.pure BlockUnit.Tt
                                                )
                                              )
                                            ]
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.assign (|
                                            ["expr_mpos"],
                                            Some (M.get_var (| "expr_mpos_1" |))
                                          |)
                                        )) in
                                        M.pure BlockUnit.Tt
                                      )
                                    );
                                    (
                                      None,
                                      M.scope (
                                        do! ltac:(M.monadic (
                                          M.declare (|
                                            ["memPtr_4"],
                                            Some ([Literal.number 0])
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.declare (|
                                            ["size_2"],
                                            Some ([Literal.number 0])
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.assign (|
                                            ["size_2"],
                                            Some ([Literal.number 0])
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.declare (|
                                            ["memPtr_5"],
                                            Some (M.call_function (|
                                              "mload",
                                              [
                                                [Literal.number 64]
                                              ]
                                            |))
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.expr_stmt (|
                                            M.call_function (|
                                              "finalize_allocation",
                                              [
                                                M.get_var (| "memPtr_5" |);
                                                [Literal.number 64]
                                              ]
                                            |)
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.assign (|
                                            ["memPtr_4"],
                                            Some (M.get_var (| "memPtr_5" |))
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.expr_stmt (|
                                            M.call_function (|
                                              "mstore",
                                              [
                                                M.get_var (| "memPtr_5" |);
                                                [Literal.number 1]
                                              ]
                                            |)
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.expr_stmt (|
                                            M.call_function (|
                                              "mstore",
                                              [
                                                M.call_function (|
                                                  "add",
                                                  [
                                                    M.get_var (| "memPtr_5" |);
                                                    [Literal.number 32]
                                                  ]
                                                |);
                                                [Literal.string 0x6100000000000000000000000000000000000000000000000000000000000000]
                                              ]
                                            |)
                                          |)
                                        )) in
                                        do! ltac:(M.monadic (
                                          M.assign (|
                                            ["expr_mpos"],
                                            Some (M.get_var (| "memPtr_5" |))
                                          |)
                                        )) in
                                        M.pure BlockUnit.Tt
                                      )
                                    )
                                  ]
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["expr"],
                                  Some (M.call_function (|
                                    "erc7201",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.get_var (| "expr_mpos" |);
                                          [Literal.number 32]
                                        ]
                                      |);
                                      M.call_function (|
                                        "mload",
                                        [
                                          M.get_var (| "expr_mpos" |)
                                        ]
                                      |)
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPtr_6"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["size_3"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["size_3"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPtr_7"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "finalize_allocation",
                                    [
                                      M.get_var (| "memPtr_7" |);
                                      [Literal.number 64]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["memPtr_6"],
                                  Some (M.get_var (| "memPtr_7" |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "memPtr_7" |);
                                      [Literal.number 1]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.get_var (| "memPtr_7" |);
                                          [Literal.number 32]
                                        ]
                                      |);
                                      [Literal.string 0x7800000000000000000000000000000000000000000000000000000000000000]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["var"],
                                  Some (M.call_function (|
                                    "eq",
                                    [
                                      M.get_var (| "expr" |);
                                      M.call_function (|
                                        "fun_erc7201Mock",
                                        [
                                          M.get_var (| "memPtr_7" |)
                                        ]
                                      |)
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPos"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "memPos" |);
                                      M.get_var (| "var" |)
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "return",
                                    [
                                      M.get_var (| "memPos" |);
                                      [Literal.number 32]
                                    ]
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          );
                          (
                            Some (Literal.number 0xdf201a46),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "callvalue",
                                    []
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "slt",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.call_function (|
                                            "calldatasize",
                                            []
                                          |);
                                          M.call_function (|
                                            "not",
                                            [
                                              [Literal.number 3]
                                            ]
                                          |)
                                        ]
                                      |);
                                      [Literal.number 0]
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPtr_8"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["size_4"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["size_4"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPtr_9"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "finalize_allocation",
                                    [
                                      M.get_var (| "memPtr_9" |);
                                      [Literal.number 64]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["memPtr_8"],
                                  Some (M.get_var (| "memPtr_9" |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "memPtr_9" |);
                                      [Literal.number 1]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["_1"],
                                  Some (M.call_function (|
                                    "add",
                                    [
                                      M.get_var (| "memPtr_9" |);
                                      [Literal.number 32]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "_1" |);
                                      [Literal.string 0x7800000000000000000000000000000000000000000000000000000000000000]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["expr_1"],
                                  Some (M.call_function (|
                                    "erc7201",
                                    [
                                      M.get_var (| "_1" |);
                                      M.call_function (|
                                        "mload",
                                        [
                                          M.get_var (| "memPtr_9" |)
                                        ]
                                      |)
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPtr_10"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["size_5"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["size_5"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPtr_11"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "finalize_allocation",
                                    [
                                      M.get_var (| "memPtr_11" |);
                                      [Literal.number 64]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["memPtr_10"],
                                  Some (M.get_var (| "memPtr_11" |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "memPtr_11" |);
                                      [Literal.number 1]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.get_var (| "memPtr_11" |);
                                          [Literal.number 32]
                                        ]
                                      |);
                                      [Literal.string 0x7800000000000000000000000000000000000000000000000000000000000000]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["var_1"],
                                  Some (M.call_function (|
                                    "eq",
                                    [
                                      M.get_var (| "expr_1" |);
                                      M.call_function (|
                                        "fun_erc7201Mock",
                                        [
                                          M.get_var (| "memPtr_11" |)
                                        ]
                                      |)
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPos_1"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "memPos_1" |);
                                      M.get_var (| "var_1" |)
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "return",
                                    [
                                      M.get_var (| "memPos_1" |);
                                      [Literal.number 32]
                                    ]
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          )
                        ]
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "revert",
                    [
                      [Literal.number 0];
                      [Literal.number 0]
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          )) in
          M.pure BlockUnit.Tt
        );
    |}.
  End deployed.
End C.

Import Ltac2.

Definition codes : list Code.t :=
  ltac2:(
    let codes := Code.get_codes () in
    exact $codes
  ).
