(* Generated by rocq-of-solidity *)
Require Import RocqOfSolidity.RocqOfSolidity.

Module C.
  Definition code : Code.t := {|
    Code.name := "C_6";
    Code.hex_name := 0x435f360000000000000000000000000000000000000000000000000000000000;
    Code.functions :=
      [
        Code.Function.make (
          "allocate_unbounded",
          [],
          ["memPtr"],
          M.scope (
            do! ltac:(M.monadic (
              M.assign (|
                ["memPtr"],
                Some (M.call_function (|
                  "mload",
                  [
                    [Literal.number 64]
                  ]
                |))
              |)
            )) in
            M.pure BlockUnit.Tt
          )
        );
        Code.Function.make (
          "revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb",
          [],
          [],
          M.scope (
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "revert",
                  [
                    [Literal.number 0];
                    [Literal.number 0]
                  ]
                |)
              |)
            )) in
            M.pure BlockUnit.Tt
          )
        );
        Code.Function.make (
          "constructor_C_6",
          [],
          [],
          M.scope (
            M.pure BlockUnit.Tt
          )
        )
      ];
    Code.body :=
      M.scope (
        do! ltac:(M.monadic (
          M.expr_stmt (|
            M.call_function (|
              "mstore",
              [
                [Literal.number 64];
                M.call_function (|
                  "memoryguard",
                  [
                    [Literal.number 128]
                  ]
                |)
              ]
            |)
          |)
        )) in
        do! ltac:(M.monadic (
          M.if_ (|
            M.call_function (|
              "callvalue",
              []
            |),
            M.scope (
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb",
                    []
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          |)
        )) in
        do! ltac:(M.monadic (
          M.expr_stmt (|
            M.call_function (|
              "constructor_C_6",
              []
            |)
          |)
        )) in
        do! ltac:(M.monadic (
          M.declare (|
            ["_1"],
            Some (M.call_function (|
              "allocate_unbounded",
              []
            |))
          |)
        )) in
        do! ltac:(M.monadic (
          M.expr_stmt (|
            M.call_function (|
              "codecopy",
              [
                M.get_var (| "_1" |);
                M.call_function (|
                  "dataoffset",
                  [
                    [Literal.string 0x435f365f6465706c6f7965640000000000000000000000000000000000000000]
                  ]
                |);
                M.call_function (|
                  "datasize",
                  [
                    [Literal.string 0x435f365f6465706c6f7965640000000000000000000000000000000000000000]
                  ]
                |)
              ]
            |)
          |)
        )) in
        do! ltac:(M.monadic (
          M.expr_stmt (|
            M.call_function (|
              "return",
              [
                M.get_var (| "_1" |);
                M.call_function (|
                  "datasize",
                  [
                    [Literal.string 0x435f365f6465706c6f7965640000000000000000000000000000000000000000]
                  ]
                |)
              ]
            |)
          |)
        )) in
        M.pure BlockUnit.Tt
      );
  |}.

  Module deployed.
    Definition code : Code.t := {|
      Code.name := "C_6_deployed";
      Code.hex_name := 0x435f365f6465706c6f7965640000000000000000000000000000000000000000;
      Code.functions :=
        [
          Code.Function.make (
            "shift_right_224_unsigned",
            ["value"],
            ["newValue"],
            M.scope (
              do! ltac:(M.monadic (
                M.assign (|
                  ["newValue"],
                  Some (M.call_function (|
                    "shr",
                    [
                      [Literal.number 224];
                      M.get_var (| "value" |)
                    ]
                  |))
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "allocate_unbounded",
            [],
            ["memPtr"],
            M.scope (
              do! ltac:(M.monadic (
                M.assign (|
                  ["memPtr"],
                  Some (M.call_function (|
                    "mload",
                    [
                      [Literal.number 64]
                    ]
                  |))
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb",
            [],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "revert",
                    [
                      [Literal.number 0];
                      [Literal.number 0]
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "revert_error_dbdddcbe895c83990c08b3492a0e83918d802a52331272ac6fdb6a7c4aea3b1b",
            [],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "revert",
                    [
                      [Literal.number 0];
                      [Literal.number 0]
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "abi_decode_tuple_",
            ["headStart"; "dataEnd"],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "slt",
                    [
                      M.call_function (|
                        "sub",
                        [
                          M.get_var (| "dataEnd" |);
                          M.get_var (| "headStart" |)
                        ]
                      |);
                      [Literal.number 0]
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert_error_dbdddcbe895c83990c08b3492a0e83918d802a52331272ac6fdb6a7c4aea3b1b",
                          []
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "abi_encode_tuple__to__fromStack",
            ["headStart"],
            ["tail"],
            M.scope (
              do! ltac:(M.monadic (
                M.assign (|
                  ["tail"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "headStart" |);
                      [Literal.number 0]
                    ]
                  |))
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "external_fun_f_5",
            [],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "callvalue",
                    []
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb",
                          []
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "abi_decode_tuple_",
                    [
                      [Literal.number 4];
                      M.call_function (|
                        "calldatasize",
                        []
                      |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "fun_f_5",
                    []
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["memPos"],
                  Some (M.call_function (|
                    "allocate_unbounded",
                    []
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["memEnd"],
                  Some (M.call_function (|
                    "abi_encode_tuple__to__fromStack",
                    [
                      M.get_var (| "memPos" |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "return",
                    [
                      M.get_var (| "memPos" |);
                      M.call_function (|
                        "sub",
                        [
                          M.get_var (| "memEnd" |);
                          M.get_var (| "memPos" |)
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "revert_error_42b3090547df1d2001c96683413b8cf91c1b902ef5e3cb8d9f6f304cf7446f74",
            [],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "revert",
                    [
                      [Literal.number 0];
                      [Literal.number 0]
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "fun_f_5",
            [],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.scope (
                  do! ltac:(M.monadic (
                    M.declare (|
                      ["usr$x"],
                      Some (M.call_function (|
                        "msize",
                        []
                      |))
                    |)
                  )) in
                  M.pure BlockUnit.Tt
                )
              )) in
              M.pure BlockUnit.Tt
            )
          )
        ];
      Code.body :=
        M.scope (
          do! ltac:(M.monadic (
            M.expr_stmt (|
              M.call_function (|
                "mstore",
                [
                  [Literal.number 64];
                  [Literal.number 128]
                ]
              |)
            |)
          )) in
          do! ltac:(M.monadic (
            M.if_ (|
              M.call_function (|
                "iszero",
                [
                  M.call_function (|
                    "lt",
                    [
                      M.call_function (|
                        "calldatasize",
                        []
                      |);
                      [Literal.number 4]
                    ]
                  |)
                ]
              |),
              M.scope (
                do! ltac:(M.monadic (
                  M.declare (|
                    ["selector"],
                    Some (M.call_function (|
                      "shift_right_224_unsigned",
                      [
                        M.call_function (|
                          "calldataload",
                          [
                            [Literal.number 0]
                          ]
                        |)
                      ]
                    |))
                  |)
                )) in
                do! ltac:(M.monadic (
                  M.switch (|
                    M.get_var (| "selector" |),
                    [
                      (
                        Some (Literal.number 0x26121ff0),
                        M.scope (
                          do! ltac:(M.monadic (
                            M.expr_stmt (|
                              M.call_function (|
                                "external_fun_f_5",
                                []
                              |)
                            |)
                          )) in
                          M.pure BlockUnit.Tt
                        )
                      );
                      (
                        None,
                        M.scope (
                          M.pure BlockUnit.Tt
                        )
                      )
                    ]
                  |)
                )) in
                M.pure BlockUnit.Tt
              )
            |)
          )) in
          do! ltac:(M.monadic (
            M.expr_stmt (|
              M.call_function (|
                "revert_error_42b3090547df1d2001c96683413b8cf91c1b902ef5e3cb8d9f6f304cf7446f74",
                []
              |)
            |)
          )) in
          M.pure BlockUnit.Tt
        );
    |}.
  End deployed.
End C.

Import Ltac2.

Definition codes : list Code.t :=
  ltac2:(
    let codes := Code.get_codes () in
    exact $codes
  ).
