(* Generated by rocq-of-solidity *)
Require Import RocqOfSolidity.RocqOfSolidity.

Module C.
  Definition code : Code.t := {|
    Code.name := "C_105";
    Code.hex_name := 0x435f313035000000000000000000000000000000000000000000000000000000;
    Code.functions :=
      [
        
      ];
    Code.body :=
      M.scope (
        do! ltac:(M.monadic (
          M.scope (
            do! ltac:(M.monadic (
              M.declare (|
                ["_1"],
                Some (M.call_function (|
                  "memoryguard",
                  [
                    [Literal.number 0x80]
                  ]
                |))
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "mstore",
                  [
                    [Literal.number 64];
                    M.get_var (| "_1" |)
                  ]
                |)
              |)
            )) in
            do! ltac:(M.monadic (
              M.if_ (|
                M.call_function (|
                  "callvalue",
                  []
                |),
                M.scope (
                  do! ltac:(M.monadic (
                    M.expr_stmt (|
                      M.call_function (|
                        "revert",
                        [
                          [Literal.number 0];
                          [Literal.number 0]
                        ]
                      |)
                    |)
                  )) in
                  M.pure BlockUnit.Tt
                )
              |)
            )) in
            do! ltac:(M.monadic (
              M.declare (|
                ["_2"],
                Some (M.call_function (|
                  "datasize",
                  [
                    [Literal.string 0x435f3130355f6465706c6f796564000000000000000000000000000000000000]
                  ]
                |))
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "codecopy",
                  [
                    M.get_var (| "_1" |);
                    M.call_function (|
                      "dataoffset",
                      [
                        [Literal.string 0x435f3130355f6465706c6f796564000000000000000000000000000000000000]
                      ]
                    |);
                    M.get_var (| "_2" |)
                  ]
                |)
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "return",
                  [
                    M.get_var (| "_1" |);
                    M.get_var (| "_2" |)
                  ]
                |)
              |)
            )) in
            M.pure BlockUnit.Tt
          )
        )) in
        M.pure BlockUnit.Tt
      );
  |}.

  Module deployed.
    Definition code : Code.t := {|
      Code.name := "C_105_deployed";
      Code.hex_name := 0x435f3130355f6465706c6f796564000000000000000000000000000000000000;
      Code.functions :=
        [
          Code.Function.make (
            "abi_encode_uint256_address_bool",
            ["headStart"; "value0"; "value1"; "value2"],
            ["tail"],
            M.scope (
              do! ltac:(M.monadic (
                M.assign (|
                  ["tail"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "headStart" |);
                      [Literal.number 96]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "headStart" |);
                      M.get_var (| "value0" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "headStart" |);
                          [Literal.number 32]
                        ]
                      |);
                      M.call_function (|
                        "and",
                        [
                          M.get_var (| "value1" |);
                          M.call_function (|
                            "sub",
                            [
                              M.call_function (|
                                "shl",
                                [
                                  [Literal.number 160];
                                  [Literal.number 1]
                                ]
                              |);
                              [Literal.number 1]
                            ]
                          |)
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "headStart" |);
                          [Literal.number 64]
                        ]
                      |);
                      M.call_function (|
                        "iszero",
                        [
                          M.call_function (|
                            "iszero",
                            [
                              M.get_var (| "value2" |)
                            ]
                          |)
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          )
        ];
      Code.body :=
        M.scope (
          do! ltac:(M.monadic (
            M.scope (
              do! ltac:(M.monadic (
                M.declare (|
                  ["_1"],
                  Some (M.call_function (|
                    "memoryguard",
                    [
                      [Literal.number 0x80]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      [Literal.number 64];
                      M.get_var (| "_1" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "iszero",
                    [
                      M.call_function (|
                        "lt",
                        [
                          M.call_function (|
                            "calldatasize",
                            []
                          |);
                          [Literal.number 4]
                        ]
                      |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.switch (|
                        M.call_function (|
                          "shr",
                          [
                            [Literal.number 224];
                            M.call_function (|
                              "calldataload",
                              [
                                [Literal.number 0]
                              ]
                            |)
                          ]
                        |),
                        [
                          (
                            Some (Literal.number 0x05d4577e),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "callvalue",
                                    []
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "slt",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.call_function (|
                                            "calldatasize",
                                            []
                                          |);
                                          M.call_function (|
                                            "not",
                                            [
                                              [Literal.number 3]
                                            ]
                                          |)
                                        ]
                                      |);
                                      [Literal.number 0]
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "sstore",
                                    [
                                      [Literal.number 0x2e];
                                      [Literal.number 0x08]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["value"],
                                  Some (M.call_function (|
                                    "or",
                                    [
                                      M.call_function (|
                                        "and",
                                        [
                                          M.call_function (|
                                            "sload",
                                            [
                                              [Literal.number 47]
                                            ]
                                          |);
                                          M.call_function (|
                                            "shl",
                                            [
                                              [Literal.number 168];
                                              [Literal.number 0xffffffffffffffffffffff]
                                            ]
                                          |)
                                        ]
                                      |);
                                      [Literal.number 0x0def]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "sstore",
                                    [
                                      [Literal.number 47];
                                      M.get_var (| "value" |)
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["tail"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["tail"],
                                  Some (M.call_function (|
                                    "add",
                                    [
                                      M.get_var (| "_1" |);
                                      [Literal.number 96]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "_1" |);
                                      [Literal.number 0x08]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.get_var (| "_1" |);
                                          [Literal.number 32]
                                        ]
                                      |);
                                      [Literal.number 0x0def]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.get_var (| "_1" |);
                                          [Literal.number 64]
                                        ]
                                      |);
                                      M.call_function (|
                                        "iszero",
                                        [
                                          M.call_function (|
                                            "iszero",
                                            [
                                              M.call_function (|
                                                "and",
                                                [
                                                  M.call_function (|
                                                    "shr",
                                                    [
                                                      [Literal.number 160];
                                                      M.get_var (| "value" |)
                                                    ]
                                                  |);
                                                  [Literal.number 0xff]
                                                ]
                                              |)
                                            ]
                                          |)
                                        ]
                                      |)
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "return",
                                    [
                                      M.get_var (| "_1" |);
                                      [Literal.number 96]
                                    ]
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          );
                          (
                            Some (Literal.number 0x11dfe474),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "callvalue",
                                    []
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "slt",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.call_function (|
                                            "calldatasize",
                                            []
                                          |);
                                          M.call_function (|
                                            "not",
                                            [
                                              [Literal.number 3]
                                            ]
                                          |)
                                        ]
                                      |);
                                      [Literal.number 0]
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "sstore",
                                    [
                                      [Literal.number 0x2a];
                                      [Literal.number 0x07]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["result"],
                                  Some (M.call_function (|
                                    "or",
                                    [
                                      M.call_function (|
                                        "and",
                                        [
                                          M.call_function (|
                                            "sload",
                                            [
                                              [Literal.number 43]
                                            ]
                                          |);
                                          M.call_function (|
                                            "shl",
                                            [
                                              [Literal.number 168];
                                              [Literal.number 0xffffffffffffffffffffff]
                                            ]
                                          |)
                                        ]
                                      |);
                                      M.call_function (|
                                        "add",
                                        [
                                          M.call_function (|
                                            "shl",
                                            [
                                              [Literal.number 160];
                                              [Literal.number 1]
                                            ]
                                          |);
                                          [Literal.number 2748]
                                        ]
                                      |)
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "sstore",
                                    [
                                      [Literal.number 43];
                                      M.get_var (| "result" |)
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPos"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["tail_1"],
                                  Some ([Literal.number 0])
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.assign (|
                                  ["tail_1"],
                                  Some (M.call_function (|
                                    "add",
                                    [
                                      M.get_var (| "memPos" |);
                                      [Literal.number 96]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.get_var (| "memPos" |);
                                      [Literal.number 0x07]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.get_var (| "memPos" |);
                                          [Literal.number 32]
                                        ]
                                      |);
                                      [Literal.number 0x0abc]
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "mstore",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.get_var (| "memPos" |);
                                          [Literal.number 64]
                                        ]
                                      |);
                                      M.call_function (|
                                        "iszero",
                                        [
                                          M.call_function (|
                                            "iszero",
                                            [
                                              M.call_function (|
                                                "and",
                                                [
                                                  M.call_function (|
                                                    "shr",
                                                    [
                                                      [Literal.number 160];
                                                      M.get_var (| "result" |)
                                                    ]
                                                  |);
                                                  [Literal.number 0xff]
                                                ]
                                              |)
                                            ]
                                          |)
                                        ]
                                      |)
                                    ]
                                  |)
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "return",
                                    [
                                      M.get_var (| "memPos" |);
                                      [Literal.number 96]
                                    ]
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          );
                          (
                            Some (Literal.number 0x6cc014de),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "callvalue",
                                    []
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "slt",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.call_function (|
                                            "calldatasize",
                                            []
                                          |);
                                          M.call_function (|
                                            "not",
                                            [
                                              [Literal.number 3]
                                            ]
                                          |)
                                        ]
                                      |);
                                      [Literal.number 0]
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["_2"],
                                  Some (M.call_function (|
                                    "sload",
                                    [
                                      [Literal.number 42]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["_3"],
                                  Some (M.call_function (|
                                    "sload",
                                    [
                                      [Literal.number 43]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPos_1"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "return",
                                    [
                                      M.get_var (| "memPos_1" |);
                                      M.call_function (|
                                        "sub",
                                        [
                                          M.call_function (|
                                            "abi_encode_uint256_address_bool",
                                            [
                                              M.get_var (| "memPos_1" |);
                                              M.get_var (| "_2" |);
                                              M.call_function (|
                                                "and",
                                                [
                                                  M.get_var (| "_3" |);
                                                  M.call_function (|
                                                    "sub",
                                                    [
                                                      M.call_function (|
                                                        "shl",
                                                        [
                                                          [Literal.number 160];
                                                          [Literal.number 1]
                                                        ]
                                                      |);
                                                      [Literal.number 1]
                                                    ]
                                                  |)
                                                ]
                                              |);
                                              M.call_function (|
                                                "and",
                                                [
                                                  M.call_function (|
                                                    "shr",
                                                    [
                                                      [Literal.number 160];
                                                      M.get_var (| "_3" |)
                                                    ]
                                                  |);
                                                  [Literal.number 0xff]
                                                ]
                                              |)
                                            ]
                                          |);
                                          M.get_var (| "memPos_1" |)
                                        ]
                                      |)
                                    ]
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          );
                          (
                            Some (Literal.number 0xa314150f),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "callvalue",
                                    []
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "slt",
                                    [
                                      M.call_function (|
                                        "add",
                                        [
                                          M.call_function (|
                                            "calldatasize",
                                            []
                                          |);
                                          M.call_function (|
                                            "not",
                                            [
                                              [Literal.number 3]
                                            ]
                                          |)
                                        ]
                                      |);
                                      [Literal.number 0]
                                    ]
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["_4"],
                                  Some (M.call_function (|
                                    "sload",
                                    [
                                      [Literal.number 46]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["_5"],
                                  Some (M.call_function (|
                                    "sload",
                                    [
                                      [Literal.number 47]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPos_2"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "return",
                                    [
                                      M.get_var (| "memPos_2" |);
                                      M.call_function (|
                                        "sub",
                                        [
                                          M.call_function (|
                                            "abi_encode_uint256_address_bool",
                                            [
                                              M.get_var (| "memPos_2" |);
                                              M.get_var (| "_4" |);
                                              M.call_function (|
                                                "and",
                                                [
                                                  M.get_var (| "_5" |);
                                                  M.call_function (|
                                                    "sub",
                                                    [
                                                      M.call_function (|
                                                        "shl",
                                                        [
                                                          [Literal.number 160];
                                                          [Literal.number 1]
                                                        ]
                                                      |);
                                                      [Literal.number 1]
                                                    ]
                                                  |)
                                                ]
                                              |);
                                              M.call_function (|
                                                "and",
                                                [
                                                  M.call_function (|
                                                    "shr",
                                                    [
                                                      [Literal.number 160];
                                                      M.get_var (| "_5" |)
                                                    ]
                                                  |);
                                                  [Literal.number 0xff]
                                                ]
                                              |)
                                            ]
                                          |);
                                          M.get_var (| "memPos_2" |)
                                        ]
                                      |)
                                    ]
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          )
                        ]
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "revert",
                    [
                      [Literal.number 0];
                      [Literal.number 0]
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          )) in
          M.pure BlockUnit.Tt
        );
    |}.
  End deployed.
End C.

Import Ltac2.

Definition codes : list Code.t :=
  ltac2:(
    let codes := Code.get_codes () in
    exact $codes
  ).
