opam-version: "2.0"
name: "rocq-of-solidity"
version: "0.1"
synopsis: "Rocq of Solidity"
description: """
Formal verification for Solidity by translation to the proof system Rocq
"""
maintainer: "Guillaume Claret <dev@clarus.me>"
authors: [
  "Formal Land <contact@formal.land>"
]
license: "MIT"
homepage: "https://github.com/formal-land/rocq-of-solidity"
bug-reports: "https://github.com/formal-land/rocq-of-solidity/issues"
dev-repo: "git+https://github.com/formal-land/rocq-of-solidity.git"
depends: [
  "rocq-core" {>= "9.0" & < "9.1"}
  "rocq-stdlib"
  "coq-coqutil" {>= "0.0.5"}
  "coq-hammer"
  "ocaml" {>= "4.08"}
]
build: [
  [make]
]
